name: CICD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Generate Deployment Package
        run: zip -r nodejs-app-build.zip
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'caller-app-backend'
          environment_name: 'caller-app-backend-env'
          version_label: 1
          region: ap-southeast-2
          deployment_package: deploy.zip
